name: "Common AI documentation workflow"
on:
  push:
    branches:
      - main
    paths:
      - "cmn_ai/**"
  pull_request:
    branches:
      - main
    paths:
      - "cmn_ai/**"
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install self
        run: poetry install
      - name: Execute tests
        run: mkdocs gh-deploy --force
