name: "Common AI test workflow"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install self
        run: |
          poetry install
      - name: Execute tests
        run: |
          poetry run pytest
