name: "Common AI test workflow"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up
        uses: actions/setup-python@v4
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: install self
        run: |
          poetry install
      - name: test with pytest
        run: |
          poetry run pytest
